hugoblox:
  schema: "2.0"
  identity:
    name: Mariia Koval
    type: person
    tagline: Economics and Statistics | Amherst College
    description: ""
  theme:
    mode: system
    pack: minimal
    colors:
      primary: blue
      secondary: gray
      neutral: ""
    colors_light:
      primary: blue
      secondary: gray
      neutral: gray
    colors_dark:
      primary: slate
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
